# Generated by Django 4.2.3 on 2024-03-29 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedtimedb',
            name='course',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trackedTimeUnderCourse', to='firstApp.course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CourseUnderUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='topic',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TopicUnderCourse', to='firstApp.course'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TopicUnderUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trackedtimedb',
            name='topic',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trackedTimeUnderTopic', to='firstApp.topic'),
        ),
        migrations.AlterField(
            model_name='trackedtimedb',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackedTimeUnderUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
