# Generated by Django 4.2.3 on 2024-02-05 15:41

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuserdb',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(default='Asia/Dhaka'),
        ),
    ]
