# Generated by Django 4.2.3 on 2024-02-05 15:42

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0002_myuserdb_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuserdb',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(default='Asia/Dhaka', null=True),
        ),
    ]
