# Generated by Django 4.2.3 on 2024-03-16 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0004_course_topic_trackedtimedb_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TopicRelatedName', to='firstApp.course'),
        ),
        migrations.AlterField(
            model_name='trackedtimedb',
            name='topic',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TrackedTimeRelatedName', to='firstApp.topic'),
        ),
    ]
