# Generated by Django 4.2.3 on 2024-03-16 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0005_alter_topic_course_alter_trackedtimedb_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedtimedb',
            name='session',
            field=models.CharField(default=None, max_length=900, null=True),
        ),
    ]
